[project]
name = "meteorite-dash"
version = "0.1.0"
description = "A small PyGame-CE based game about dodging incoming meteorites, shooting debries and attacking enemies."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame-ce>=2.5.7",
]

[project.scripts]
meteorite-dash = "main:main"
